## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('woss-aloha-example', ['internet', 'mobility', 'stats', 'applications', 'uan', 'woss-ns3'])
    obj.source = 'woss-aloha-example.cc'

    #Temporarily disable "unused variable" warning, until NetCDF-C++4 fixes it
    if bld.env['NETCDF']:
      obj.env.append_value('CXXFLAGS', '-Wno-unused-variable')
