## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('woss-aloha-example', ['netanim', 'internet', 'mobility', 'stats', 'applications', 'uan', 'woss-ns3'])
    obj.source = 'woss-aloha-example.cc'

